name: TR Cloudstream Depolarını Oluştur

concurrency: 
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'
      - '.github/scripts/fetch_plugins.py'
      - '.github/workflows/update_plugins.yml'
      - 'go/index.html'
      - 'go/redirect.js'
      - 'data.json'
      - 'index.html'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          path: "src"
          token: ${{ secrets.ACTIONHELPER }}

      - name: Checkout builds
        uses: actions/checkout@master
        with:
          ref: "builds"
          path: "builds"
      
      - name: Clean old builds
        run: rm $GITHUB_WORKSPACE/builds/*.cs3

      - name: Setup JDK 18
        uses: actions/setup-java@v1
        with:
          java-version: 18

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.name "ActionHelper"
          git config --local user.email "212895703+ActionHelper@users.noreply.github.com"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || exit 0
          git push --force
