name: Günlük Eklenti Güncellemesi

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  update_plugins:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu çek
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Python'u kur
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Gereksinimleri yükle
        run: pip install requests

      - name: Eklenti verisini güncelle
        env:
          ACTIONHELPER: ${{ secrets.ACTIONHELPER }}
        run: python .github/scripts/fetch_plugins.py

      - name: Güncellenen JSON dosyasını commitle
        run: |
          git config --global user.name "ActionHelper"
          git config --global user.email "212895703+ActionHelper@users.noreply.github.com"
          git add data.json datas/
          git commit -m "🚀 Eklenti listesi güncellendi [ci skip]" || echo "✅ Değişiklik yok!"

      # - name: Gerekirse rebase yap
      #   run: git pull --rebase origin main || echo "⚠️ Rebase sırasında hata oluştu, değişiklik yok veya çözülmesi gereken bir çatışma olabilir."

      - name: Pushla
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONHELPER }}
        run: |
          git push https://x-access-token:${{ secrets.ACTIONHELPER }}@github.com/GitLatte/repos.git main || echo "⚠️ Push sırasında hata oluştu."
